import time
import pyautogui
import webbrowser
import keyboard  # Türkçe karakter desteği için

# ChatGPT sayfasını aç
webbrowser.open("https://chatgpt.com/c/68176826-24b0-8003-bd95-da5f247773a7")
input("✍️ ChatGPT yüklensin ve hazır olunca ENTER'a bas: ")

# Yazma kutusunun koordinatları
yazi_kutusu_x = 1449
yazi_kutusu_y = 981

# Temel prompt
temel_prompt = " "

# Çok satırlı prompt listesi
raw_prompts = '''
1. Realistic: Analyze multiple existing artworks made in Realistic style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
2. Hyperrealistic: Analyze multiple existing artworks made in Hyperrealistic style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
3. 3D: Analyze multiple existing artworks made in 3D style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
4. 2D: Analyze multiple existing artworks made in 2D style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
5. Anime: Analyze multiple existing artworks made in Anime style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
6. Manga: Analyze multiple existing artworks made in Manga style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
7. Low-poly: Analyze multiple existing artworks made in Low-poly style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
8. Pixel Art: Analyze multiple existing artworks made in Pixel Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
9. Isometric: Analyze multiple existing artworks made in Isometric style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
10. Vector Art: Analyze multiple existing artworks made in Vector Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
11. Oil Painting: Analyze multiple existing artworks made in Oil Painting style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
12. Watercolor: Analyze multiple existing artworks made in Watercolor style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
13. Pencil Sketch: Analyze multiple existing artworks made in Pencil Sketch style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
14. Ink Drawing: Analyze multiple existing artworks made in Ink Drawing style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
15. Charcoal Drawing: Analyze multiple existing artworks made in Charcoal Drawing style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
16. Pastel Drawing: Analyze multiple existing artworks made in Pastel Drawing style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
17. Acrylic Painting: Analyze multiple existing artworks made in Acrylic Painting style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
18. Digital Painting: Analyze multiple existing artworks made in Digital Painting style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
19. Concept Art: Analyze multiple existing artworks made in Concept Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
20. Matte Painting: Analyze multiple existing artworks made in Matte Painting style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
21. Photo Merge (Photobash): Analyze multiple existing artworks made in Photo Merge (Photobash) style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
22. Collage: Analyze multiple existing artworks made in Collage style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
23. Neon Art: Analyze multiple existing artworks made in Neon Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
24. Synthwave: Analyze multiple existing artworks made in Synthwave style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
25. Cyberpunk: Analyze multiple existing artworks made in Cyberpunk style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
26. Steampunk: Analyze multiple existing artworks made in Steampunk style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
27. Fantasy Art: Analyze multiple existing artworks made in Fantasy Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
28. Sci-fi Art: Analyze multiple existing artworks made in Sci-fi Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
29. Abstract: Analyze multiple existing artworks made in Abstract style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
30. Surrealism: Analyze multiple existing artworks made in Surrealism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
31. Minimalism: Analyze multiple existing artworks made in Minimalism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
32. Pop Art: Analyze multiple existing artworks made in Pop Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
33. Art Nouveau: Analyze multiple existing artworks made in Art Nouveau style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
34. Impressionism: Analyze multiple existing artworks made in Impressionism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
35. Expressionism: Analyze multiple existing artworks made in Expressionism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
36. Cubism: Analyze multiple existing artworks made in Cubism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
37. Dark Fantasy: Analyze multiple existing artworks made in Dark Fantasy style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
38. Noir Style: Analyze multiple existing artworks made in Noir Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
39. Storybook Illustration: Analyze multiple existing artworks made in Storybook Illustration style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
40. Children's Book Style: Analyze multiple existing artworks made in Children's Book Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
41. Paper Cutout Art: Analyze multiple existing artworks made in Paper Cutout Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
42. Graffiti: Analyze multiple existing artworks made in Graffiti style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
43. Sticker Art: Analyze multiple existing artworks made in Sticker Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
44. Ink Wash Style: Analyze multiple existing artworks made in Ink Wash Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
45. Doodle Art: Analyze multiple existing artworks made in Doodle Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
46. Cartoon Style: Analyze multiple existing artworks made in Cartoon Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
47. Silhouette Art: Analyze multiple existing artworks made in Silhouette Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
48. Stylized 3D: Analyze multiple existing artworks made in Stylized 3D style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
49. Flat Design: Analyze multiple existing artworks made in Flat Design style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
50. Vintage Style: Analyze multiple existing artworks made in Vintage Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
51. VHS Glitch Style: Analyze multiple existing artworks made in VHS Glitch Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
52. Retrofuturism: Analyze multiple existing artworks made in Retrofuturism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
53. Brutalism: Analyze multiple existing artworks made in Brutalism style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
54. Street Art: Analyze multiple existing artworks made in Street Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
55. Hand-Painted Style: Analyze multiple existing artworks made in Hand-Painted Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
56. Rotoscope Style: Analyze multiple existing artworks made in Rotoscope Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
57. Glitch Art: Analyze multiple existing artworks made in Glitch Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
58. Biomechanical Style: Analyze multiple existing artworks made in Biomechanical Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
59. Line Art: Analyze multiple existing artworks made in Line Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
60. Cel-shading: Analyze multiple existing artworks made in Cel-shading style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
61. Shadow Art: Analyze multiple existing artworks made in Shadow Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
62. Monochrome Style: Analyze multiple existing artworks made in Monochrome Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
63. Sketchbook Style: Analyze multiple existing artworks made in Sketchbook Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
64. Brushstroke Style: Analyze multiple existing artworks made in Brushstroke Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
65. Stone Relief Style: Analyze multiple existing artworks made in Stone Relief Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
66. Metallic Style: Analyze multiple existing artworks made in Metallic Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
67. Mandala Art: Analyze multiple existing artworks made in Mandala Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
68. Mural Style: Analyze multiple existing artworks made in Mural Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
69. Shaded Pixel Art: Analyze multiple existing artworks made in Shaded Pixel Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
70. Mosaic Art: Analyze multiple existing artworks made in Mosaic Art style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
71. Geometric Style: Analyze multiple existing artworks made in Geometric Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
72. Animation Sketch Style: Analyze multiple existing artworks made in Animation Sketch Style style and create a new image that represents the average look and feel of those works. Apply this style consistently across the entire image. The scene must include: a cozy cottage, a sleeping cat, blooming flowers, butterflies, and warm sunlight.
'''

# Satırları listeye dönüştür
prompt_listesi = [satir.strip() for satir in raw_prompts.strip().split('\n') if satir.strip()]

# Döngüyle sırayla gönder
for prompt in prompt_listesi:
    pyautogui.click(x=460, y=570)
    time.sleep(1)
    keyboard.send("ctrl+a")
    time.sleep(1)
    keyboard.send("del")
    time.sleep(1)
    tam_komut =  prompt + temel_prompt
    keyboard.write(tam_komut, delay=0.05)  # Türkçe karakter desteğiyle yaz
    #pyautogui.click(x=545, y=987)  # "Gönder" butonuna tıklama (ENTER yerine)
    #keyboard.send("ctrl+enter")  # Gönderme: Ctrl + Enter
    pyautogui.click(x=803, y=970)
    time.sleep(3)
    #pyautogui.click(x=78, y=543)
    
    print(f"✅ Gönderildi: {tam_komut}")
    time.sleep(30)

print("🎉 Tüm komutlar başarıyla gönderildi.")
